name: guardian
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  google_sign_in: ^6.1.4
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/guardian_logo.png
    - assets/images/google_icon.png

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_24pt-Regular.ttf
        - asset: assets/fonts/Inter_24pt-Italic.ttf
          style: italic
        - asset: assets/fonts/Inter_24pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_24pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_24pt-BoldItalic.ttf
          weight: 700
          style: italic

# --- APP ICON ---
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/guardian_logo.png
  min_sdk_android: 21
  remove_alpha_ios: true

# --- SPLASH SCREEN ---
flutter_native_splash:
  color: "#F3F4F6"
  color_dark: "#181A1B"
  image: assets/images/guardian_logo2.png
  image_dark: assets/images/guardian_logo2.png
  android: true
  ios: true
  web: false

  android_gravity: center
  ios_content_mode: center

  android_12:
    color: "#F3F4F6"
    color_dark: "#181A1B"
    image: assets/images/guardian_logo2.png
    image_dark: assets/images/guardian_logo2.png
    icon_background_color: "#F3F4F6"
    icon_background_color_dark: "#181A1B"
